apiVersion: v1
kind: Service
metadata:
  name: kubetest-service
spec:
  type: NodePort
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
  selector:
    app: kubetest
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
